### ISSUE TITLE
Another File: find_replace_in_files_input

### ISSUE THREAD

**Issue by jaredashworth** [tyleransom/bash-scripts#1]
This file is stored in bin, but can be called from anywhere. It begins the find and replace starting at the directory you are in when called and then replaces to all subdirectories. The advantage of find_replace_in_files is that you don't have to edit the shell script, you just have to give it (correctly-formatted) inputs.

[find_replace_in_files_input.txt](https://github.com/tyleransom/bash-scripts/files/828772/find_replace_in_files_input.txt)

**Comment by tyleransom** [comment]
This is great. Please add this in a PR and I'll be happy to incorporate it!

**Comment by jaredashworth** [comment]
Done and done. Closing issue.
